security:
    # Password hashers configuration for all environments
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: auto
            # You can adjust these settings for production
            cost: 4 # For bcrypt
            time_cost: 3 # For Argon2i
            memory_cost: 10 # For Argon2i
        App\Entity\User:
            algorithm: auto
    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false  # Disable security only for dev tools and assets

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginFormAuthenticator
            access_denied_url: app_access_denied
            logout:
                path: app_logout
                target: app_login
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path: /
                always_remember_me: false

    # Role hierarchy for tiered access
    role_hierarchy:
        ROLE_PREMIUM: ROLE_USER
        ROLE_ADMIN: [ROLE_PREMIUM, ROLE_USER]

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # Proper access control with specific public routes
    access_control:
        # Public routes (no login required)
        - { path: ^/login$, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/reset-password, roles: PUBLIC_ACCESS }
        - { path: ^/$, roles: PUBLIC_ACCESS }
        
        # Development access - keep this commented out in production
        - { path: ^/dev/, roles: PUBLIC_ACCESS }
        
        # Admin routes
        - { path: ^/admin, roles: ROLE_ADMIN }
        
        # Default routes (require login)
        - { path: ^/, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
